<div class="header-wrap">

    <header class="header-default navbar">
        <section class="navbar-section">
        <a href="<?=base_url('dashboard')?>" class="logo">
            <img src="<?=base_url('assets/img/logo-solid.png')?>" alt="<?php siteinfo('name'); ?>">
        </a>
    </section>
 <section class="navbar-center">
  </section>
  <section class="navbar-section">
    <a href="<?=base_url()?>" class="btn btn-white" target="_blank">View Site</a>
  </section>
    </header>

</div>
