<?php $this->start('content');?>
<div class="row">
    <div class="col-md-9 col-sm-9">
        <?php if (has_videos()) : ?>
            <div class="videos-block">
                <h3 class="heading"><span>Videos under category <?php the_category_name(); ?></span></h3>
                <h4 class="sub-heading"><span>Found <?php the_result_count(); ?> videos</span></h4>
                <?php the_breadcrumbs(); ?>
                <div class="video-listing">
                    <div class="row">
                        <?php while (videos()) : ?>
                            <div class="col-md-6 col-sm-6">
                                <?php $this->insert('partials/loop'); ?>
                            </div>
                        <?php endwhile;?>
                    </div>
                    <?php the_pagination('<ul class="video-pages">', "</ul>"); ?>
                </div>

            </div>
            <!-- ./videos-block -->
        <?php else : ?>

            <div class="empty no-content">
              <div class="empty-icon">
                <img src="<?=theme_url('img/noresults.png')?>" alt="No results" noselect="true">
            </div>
            <p class="empty-title h4">Nothing found!</p>
            <p class="empty-subtitle">Sorry no videos found for your query <strong><?php the_search_query(); ?></strong>. Please try with another query. If you are seeing this more often and think it's an internal problem, please contact the site administrator.</p>
            <div class="empty-action">
                <a class="btn btn-red-outline" href="javascript:location.reload();" rel="nofollow">Reload</a>
            </div>
        </div>
    <?php endif;?>
</div>
<!-- ./col-md-9 -->

<div class="col-md-3 col-sm-3">
    <?php $this->insert('partials/menu');?>
</div>
<!-- ./col-md-3 -->
</div>
<?php $this->end(); ?>
<?php
// Extends the base template
$this->extend('base', ['bodyClass' => 'category']);
?>
