<?php $this->start('content');?>
<?php if (has_videos()) : ?>
    <div class="videos-block">
        <h3 class="heading"><span>Trending #<?php the_search_query(); ?></span></h3>
        <h4 class="sub-heading"><span>Found <?php the_result_count(); ?> videos</span></h4>

        <div class="video-listing">
            <div class="row">
                <?php while (videos()) : ?>
                    <div class="col-md-6 col-sm-6">
                        <?php $this->insert('partials/loop'); ?>
                    </div>
                <?php endwhile;?>
            </div>

            <div class="explore-link">
                <a href="<?php the_explore_link(); ?>" rel="next" class="btn btn-block btn-green">Load more..</a></li>
            </div>
        </div>

    </div>
    <!-- ./videos-block -->
    <?php $this->insert('partials/recent-tags'); ?>
<?php else : ?>

    <div class="empty no-content">
      <div class="empty-icon">
        <img src="<?=theme_url('img/noresults.png')?>" alt="No results" noselect="true">
    </div>
    <p class="empty-title h4">Nothing found!</p>
    <p class="empty-subtitle">Sorry no videos found for your query <strong><?php the_search_query(); ?></strong>. Please try with another query. If you are seeing this more often and think it's an internal problem, please contact the site administrator.</p>
    <div class="empty-action">
        <a class="btn btn-red-outline" href="javascript:location.reload();" rel="nofollow">Reload</a>
    </div>
</div>
<?php endif;?>
</div>
</div>
<?php $this->end(); ?>
<?php
// Extends the base template
$this->extend('base', ['bodyClass' => 'home']);
?>
