<?php

use Oishy\Core\Request;
use Oishy\Core\Response;
use Oishy\Core\Router;
use Oishy\Driver\Items;
use Oishy\Driver\Registry;
use Oishy\Model\PermalinkModel;
use Oishy\Model\TagModel;
use Oishy\Model\VideoModel;

/**
 * Homepage
 */
Router::map('GET', '/', function () use ($tpl) {
    Registry::set('page.is_home', true, true);
    $q = VideoModel::getRandQuery();
    // Process for title case
    $title = title_case($q);

    Registry::set('search.query', $title);
    Registry::set('search.query_slug', $q);
    // search youtube
    $result = VideoModel::search($q);
    $videos = new Items($result);
    // Update in registry
    Registry::set('total_videos', count($result));
    Registry::set('videos', $videos);
    return $tpl->render(['index', 'home']);
});

/**
 * Process search request
 */
Router::map('POST', '/ParseSearchRequest', function () {
    $uri = VideoModel::parseSearch();
    return Response::redirect($uri, false, 301)->send(1);
});


Router::map('GET', '/page/[*:page]', function ($page) use ($tpl) {
    $tpl_name = 'page/' . $page;

    if ($tpl->exists($tpl_name)) {
        return $tpl->render($tpl_name);
    }

    return trigger_404_error();
});

Router::map('GET', '/watch', function () {
    $v = Request::get('v');
    if (!$v) {
        return trigger_404_error();
    }
    $url = PermalinkModel::getSinglePermalink($v, 'direct-download');

    return Response::redirect($url, false, 301)->send();
});


Router::map('GET', '/sitemap[hyphen_number:id]?.xml', function () {
    $n = Registry::get('route.params.id', '1');
    $n = trim($n, '-');

    if ($n == 0) {
        return trigger_404_error();
    }

    // Google recommends 50,000 links per sitemap
    $items_per_page = 50000;
    $offset = ($n - 1) * $items_per_page;
    $links = TagModel::listTags($offset, $items_per_page);

    Response::headers(['Content-type' => 'text/xml'])->send();
    echo "<?xml version='1.0' encoding='UTF-8'?>\n";
    echo "<!-- Generated by MiTube -->\n";
    echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">';

    foreach ($links as $link) {
        $url = PermalinkModel::getSearchPermalink($link['query']);
        echo "
        <url>
        <loc>{$url}</loc>
        <priority>0.80</priority>
        <changefreq>monthly</changefreq>
        </url>";
    }

    echo "\n</urlset>";
});
