<!-- Navbar -->
<nav class="navbar navbar-default" id="nav-primary">
  <div class="nav-container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#search-collapse" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<?=base_url()?>" class="navbar-brand">
        <img src="<?php theme_logo_url(); ?>" alt="<?php siteinfo('name'); ?>">
      </a>
    </div>

    <div class="collapse navbar-collapse" id="search-collapse">
      <?php $this->insert('partials/search-box'); ?>
      <ul class="nav navbar-nav navbar-right">
        <li class="<?php if (is_home()) : ?>active<?php endif;?>">
          <a href="<?=base_url()?>">Home</a>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle topics-menu" data-toggle="dropdown" href="javascript:void(0);">Categories
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <?php
              mi_list_categories(['before' => '<li class="%active%">', 'after' => '</li>']);
              ?>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
