<div class="list-video">
        <table width="100%">
            <tbody><tr>
                <td width="10%">
                    <div class="thumb"><img src="<?php the_thumbnail(); ?>" alt="<?php the_title();?>"></div>
                </td>
                <td width="90%">
                    <div class="details">
                        <h3><a href="<?php the_permalink(); ?>" title="<?php the_title();?>" rel="bookmark"><?php the_title();?></a></h3>
                        <span class="channel-details">
                            <a href="<?php the_channel_permalink(); ?>">@<?php the_channel();?></a>
                        </span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>
