<?php $this->start('content');?>
<h3 class="heading"><span>Ads Manager</span></h3>
<div class="dash-container">
    <?php alert_show('error'); ?>
    <?php alert_show('success'); ?>
    <form method="post" action="<?=base_url('dashboard/update/ads')?>">
        <div class="form-group">
            <label for="adcode_header" class="form-label">Header Adcode</label>
            <textarea class="form-input" id="adcode_header" name="adcode_header"><?php option('adcode_header')?></textarea>
            <p class="input-help">
                Insert Header Adcode. Will be shown just after the header on all pages of site. ( Excluding admin dashboard. )
            </p>
        </div>
        <div class="form-group">
            <label for="adcode_single" class="form-label">Single Video Adcode</label>
            <textarea class="form-input" id="adcode_single" name="adcode_single"><?php option('adcode_single')?></textarea>
            <p class="input-help">
                Insert single video adcode. Will be shown on single video page.
            </p>
        </div>
        <div class="form-group">
            <label for="adcode_single" class="form-label">Download Page Adcode</label>
            <textarea class="form-input" id="adcode_download" name="adcode_download"><?php option('adcode_download')?></textarea>
            <p class="input-help">
                Insert download page adcode. Will be shown on video download page.
            </p>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-blue btn-block">Update</button>
        </div>
        <?=csrf_get_token_html()?>
    </form>
</div>
    <?php $this->end();?>
    <?php
    $this->extend('base');
    ?>
