<?php $this->start('content');?>
<h3 class="heading"><span>Change Password</span></h3>
<div class="dash-container">
    <?php alert_show('error'); ?>
    <?php alert_show('success'); ?>
    <form method="post" action="<?=base_url('dashboard/update/password')?>">
        <div class="form-group">
            <label class="form-label" for="current_pass">Current Password</label>
            <input type="password" name="current_pass" id="current_pass" class="form-input">
        </div>
        <div class="form-group">
            <label class="form-label" for="new_pass">New Password</label>
            <input type="password" name="new_pass" id="new_pass" class="form-input">
        </div>
        <div class="form-group">
            <label class="form-label" for="new_pass_verify">Confirm New Password</label>
            <input type="password" name="new_pass_verify" id="new_pass_verify" class="form-input">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-blue btn-block">Change</button>
        </div>
        <?=csrf_get_token_html()?>
    </form>
</div>
<?php $this->end();?>
<?php
$this->extend('base');
?>
